builders:
  hive_built_value_generator:
    import: "package:hive_built_value_generator/hive_built_value_generator.dart"
    builder_factories: ["getBuilder"]
    build_extensions: {".dart": ["hive_built_value_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]