name: example

dependencies:
  hive_built_value:
    path: ../../hive_built_value

dev_dependencies:
  hive_built_value_generator:
    path: ../../hive_built_value_generator
  build_runner: ^2.3.3

environment:
  sdk: ">=2.17.6 <3.0.0"
