name: hive_built_value
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 2.0.9
homepage: https://github.com/hivedb/hive/tree/master/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  meta: ^1.9.1
  crypto: ^3.0.2

dev_dependencies:
  test: ^1.24.2
  mocktail: ^0.3.0
  lints: ^2.0.1
  path: ^1.8.3
  pointycastle: ^3.7.3
  build_runner: ^2.3.3
